
libname sasfiles "C:/Users/FNLNJE/Documents/My SAS Files";

data sasfiles.valid_values;
    length TBL $20 COLNAME $32 VALUE $200;
    infile datalines dsd dlm="|" truncover;
    input TBL $ COLNAME $ VALUE $;
    datalines;
LN_DTL|BRANCH_CODE|SG
LN_DTL|CNTRY_CODE|SG
LN_DTL|REGION_CODE|SG
LN_DTL|DATA_ORIGIN|SGDWH
LN_DTL|GL_CODE|00000
LN_DTL|REMOVE_RESCHEDULE_IND|(blank)
LN_DTL|REMOVE_RESTRUCTURE_IND|(blank)
LN_DTL|REPACKAGING_IND|(blank)
LN_DTL|MULTI_TIER_INT_FLG|N
LN_DTL|MULTI_TIER_INT_FLG|Y
LN_DTL|RSME_FLG|N
LN_DTL|RSME_FLG|Y
LN_DTL|SHORTFALL_FLAG|N
LN_DTL|SHORTFALL_FLAG|Y
LN_DTL|UNCOND_CANCELLED_EXP_IND|N
LN_DTL|UNCOND_CANCELLED_EXP_IND|Y
LN_DTL|DEFAULT_FLG|N
LN_DTL|DEFAULT_FLG|Y
LN_DTL|SM_FLG|N
LN_DTL|SM_FLG|Y
LN_DTL|RATING_OUTLOOK_WATCH|N
LN_DTL|RATING_OUTLOOK_WATCH|Y
LN_DTL|RESCHEDULE_FLG|N
LN_DTL|RESCHEDULE_FLG|Y
LN_DTL|RESTRUCTURED_FLG|N
LN_DTL|RESTRUCTURED_FLG|Y
LN_DTL|REPRICE_FLAG|N
LN_DTL|REPRICE_FLAG|Y
LN_DTL|WO_FLG|N
LN_DTL|WO_FLG|Y
LN_DTL|FINANCING_CODE|C
LN_DTL|FINANCING_CODE|I
LN_DTL|IFRS9_CLASS_CODE|AMRTCOST
LN_DTL|IFRS9_CLASS_CODE|FVOCI
LN_DTL|LEGAL_ENTITY_CODE|MBB-SG
LN_DTL|LEGAL_ENTITY_CODE|MSL
LN_DTL|LGD_PROD_TYPE|ESG
LN_DTL|LGD_PROD_TYPE|NON-ESG
LN_DTL|RELEASE_TYPE_CD|F
LN_DTL|RELEASE_TYPE_CD|P
LN_DTL|CREDIT_CLS_TYP_CODE|(blank)
LN_DTL|CREDIT_CLS_TYP_CODE|S01
LN_DTL|CREDIT_CLS_TYP_CODE|S03
LN_DTL|CREDIT_CLS_TYP_CODE|S05
LN_DTL|BASEL_LGD_CLS|(blank)
LN_DTL|BASEL_LGD_CLS|P 1
LN_DTL|BASEL_LGD_CLS|P 2
LN_DTL|BASEL_LGD_CLS|P 3
LN_DTL|BASEL_LGD_CLS|P 4
LN_DTL|BASEL_LGD_CLS|P 5
LN_DTL|BASEL_LGD_CLS|P 6
LN_DTL|BASEL_LGD_CLS|P 7
LN_DTL|BASEL_LGD_CLS|P 9
LN_DTL|BASEL_LGD_CLS|P 10
LN_DTL|BASEL_LGD_CLS|P 11
LN_DTL|BASEL_LGD_CLS|P 12
LN_DTL|BASEL_LGD_CLS|P 13
;
run;

proc print data=sasfiles.valid_values noobs label;
    title "SASFILES.VALID_VALUES";
    label TBL = "Table"  COLNAME = "Column"  VALUE = "Allowed value";
run;
title;
